name: Build images

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker:
    strategy:
      matrix:
        os: [fcos, ubuntu]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/kubevirt-${{ matrix.os }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
      - name: Build
        env:
          FORCE_COLOR: 3
          TAGS: ${{ steps.meta.outputs.tags }}
          IS_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}
        run: |
          npx zx ${{ matrix.os }}.js
