name: Build images on macOS

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker:
    strategy:
      matrix:
        os: [ubuntu-kubeadm-22.04]
    runs-on: macos-latest
    permissions:
      packages: write
      contents: read

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install zx
        run: |
          npm i -g zx

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v2
      - name: Set up QEMU
        run: |
          brew install qemu
      - name: Install docker
        run: |
          brew install docker
          colima start

      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/kubevirt-${{ matrix.os }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
      - name: Build
        env:
          FORCE_COLOR: 3
          TAGS: ${{ steps.meta.outputs.tags }}
          IS_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}
        run: |
          npx zx ${{ matrix.os }}.js
